### PR TITLE
Pass project type to parser before formatting

### PR DESCRIPTION
**Pull request by robinheghan**
Otherwise, formatting doesn't work for core packages.

### CODE REVIEW

**Comment by avh4** [comment]
👍 yeah, that looks good.  The one weird thing is that it'll only work if you run `gren format` (for example, `gren format ./src` won't work), but it's definitely better than nothing, and it's probably fine anyway since normal users won't need to format core modules.

**Comment by robinheghan** [comment]
Agreed.

Do you know how this affects editors and editor tooling? I assume a VSCode plugin won't actually call `gren format` on a working directory, but either pass in a file or use the `stdin` functionality.

**Comment by avh4** [comment]
> Do you know how this affects editors and editor tooling? I assume a VSCode plugin won't actually call `gren format` on a working directory, but either pass in a file or use the `stdin` functionality.

Ah, that's true.  I'm not sure what the current VSCode Elm plugin does, but most plugins have initially run elm-format on the single file after save, and then a few plugins have later switched to using the `stdin` option.  If a plugin allows formatting without saving the file, then it's definitely using the `stdin` option.

I think my future suggestion for better plugin support would be for `gren format` to take an optional flag that would tell it where the `gren.json` file is, and that would allow the project detection to work for `stdin`, and would let plugins be explicit (I've heard some plugin systems don't get good control over what the current directory is set to).

**Comment by robinheghan** [comment]
> I think my future suggestion for better plugin support

Good idea!

**Pull request merged**
