### PR TITLE
Update cabal and make tests run quickly

### PR DESCRIPTION
**Pull request by robinheghan**

### CODE REVIEW

**Comment by jhrcek** [comment]
Hello @robinheghan 
I'm just curious about which part of this PR is doing the "make tests run quickly"?

**Comment by robinheghan** [comment]
When running `cabal build -f dev` followed by `cabal build -f dev` on my local machine, cabal 3.6 will compile the compiler twice (once for the build, once for the tests). Cabal 3.8 compiles the compiler only once.

Though I didn't see that behaviour in the github action 😅

**Comment by jhrcek** [comment]
Makes sense, thank you for explanation.

I think the reason why the lib is recompiled in CI when you do `cabal test -f dev` is only after you run the tests for the first time cabal "sees" the extra test dependencies and for some reason decides to recompile everything.

I think you can achieve the "don't recompile lib when running tests" behavior by adding `--enable-tests` in build step.
You should be able to reproduce the difference when running locally too if you delete dist-newstyle:

```bash
rm dist-newstyle/ -rf
cabal build -f dev --enable-tests # will build everything including test dependencies
cabal test -f dev # won't recompile lib, will only run tests
```

**Comment by jhrcek** [comment]
Checked on my machine:

```
time ( rm -rf dist-newstyle/ && cabal build -f dev && cabal test -f dev )
real	1m5.324s
...
time ( rm -rf dist-newstyle/ && cabal build -f dev --enable-tests && cabal test -f dev )
real	0m39.791s
...
```

I guess that's one of the reasons why github action configs generated by [haskell-ci](https://github.com/haskell-CI/haskell-ci)
contain `cabal configure --enable-tests` as one of the first steps.

**Comment by robinheghan** [comment]
Thank you! Just added it to the main branch.

**Pull request merged**
