### PR TITLE
[WIP] Retain comments in the AST

### PR DESCRIPTION
**Pull request by avh4**

### CODE REVIEW

**Comment by avh4** [comment]
Notes on the WIP:

I'm trying to rely on unused-do-bind, unused-matches, and unused variables warnings to indicate remaining comments that need to be captured.

imo it's probably best to just add the comments in to the AST however makes it easiest for the parser code.  imo it's not worth making the parse more complex for the purpose of making the AST make more "sense" for how an end-user would think of the code being structured.  It'll be relatively simple to either have a normalization layer, or to make the formatting code a bit more complex to grab the comments from wherever they are.

**Comment by avh4** [comment]
Also I can't quite remember, but there's some stuff about parsing comments in https://github.com/gren-lang/compiler/compare/main...avh4/finalize-format (as of 2022-07-26) as well... I can't remember if the Parse/Parse.Space stuff there is important w/r to this branch or not.

**Comment by robinheghan** [comment]
@avh4 Just made a commit. Does my approach match what you had in mind?

**Comment by avh4** [comment]
> Does my approach match what you had in mind?

@robinheghan Yep, exactly!

I hadn't really thought about if we'd need the Comments to be `Located` or not.  Did you have a thought as to why that'd be specifically useful, or did you do that by default?

**Comment by robinheghan** [comment]
I thought it made sense in this case, this way we can just store a list of comments somewhere and use the location data to figure out where they fit in a later normalization step.

**Comment by avh4** [comment]
Replaced by https://github.com/gren-lang/compiler/pull/132

**Pull request closed without merging**
